"""`anima animus bench`: latency of a provider on the question kinds phase 2 asks (PHASE-2-PLAN S2).

Runs each sample question alone, then `concurrency` at once (six agents sharing one GPU), and
appends a table to docs/ANIMUS-BENCH.md so the model choice rests on measured numbers.
"""
from __future__ import annotations

import asyncio
import statistics
import time
from pathlib import Path
from typing import Any

from anima.animus.queue import Request, check_schema

PATCH = {"type": "object", "required": ["changes"]}
SAMPLES: list[dict[str, Any]] = [
    {"kind": "mob_risk", "question": "A creature you have no knowledge of is in the room. How dangerous is it "
     "for you to fight it now? Answer safe, risky or deadly.",
     "context": {"me": {"level": 8, "hp_pct": 92, "class_hint": "fighter"},
                 "creature": "A large, hairy troll is standing here, picking its teeth.",
                 "zone_levels": "1-10", "party_here": 6},
     "schema": {"type": "enum", "values": ["safe", "risky", "deadly"]}, "default": "risky"},
    {"kind": "stuck", "question": "The same behavior has run for 6 minutes without progress. Propose knob changes "
     "for yourself, or none.",
     "context": {"behavior": "go_home", "room": "A City Square", "refused": {"no_target": 0},
                 "move_failed": [{"dir": "east", "reason": "locked"}] * 5, "time": "night",
                 "knobs": {"policy.hunt_min_hp": 60}},
     "schema": PATCH, "default": {"changes": []}},
    {"kind": "self_tune", "question": "Over the last 20 minutes the leader waited for you 9 minutes while you "
     "slept to recover mana. Propose knob changes for yourself, or none.",
     "context": {"mine": {"rest_mp_pct": 45, "rest_pct": 30, "mp_max": 141},
                 "last_20min": {"waited_for_me_min": 9.1, "kills": 3, "lowest_mp_pct": 18, "heals_cast": 2},
                 "knobs": {"policy.rest_mp_pct": "0..90, step 20", "policy.rest_pct": "20..70, step 15"},
                 "locked": {}},
     "schema": PATCH, "default": {"changes": []}},
]


def _req(s: dict[str, Any], tier: str, i: int, timeout: float) -> Request:
    return Request(id=f"bench:{s['kind']}:{i}", agent="Bench", asker=f"bench/{s['kind']}", tier=tier,
                   priority="routine", question_kind=s["kind"], question=s["question"], context=s["context"],
                   answer_schema=s["schema"], timeout_s=timeout, default=s["default"], created=time.monotonic())


async def _one(provider, r: Request) -> tuple[float, bool, str]:
    t0 = time.monotonic()
    try:
        rep = await asyncio.wait_for(provider.answer(r), r.timeout_s)
        return time.monotonic() - t0, check_schema(rep.answer, r.answer_schema), repr(rep.answer)[:60]
    except Exception as e:                              # timeouts and provider errors count as failures
        return time.monotonic() - t0, False, type(e).__name__


async def run(provider, tier: str, repeat: int, concurrency: int, timeout: float) -> list[dict[str, Any]]:
    rows = []
    for s in SAMPLES:
        alone = [await _one(provider, _req(s, tier, i, timeout)) for i in range(repeat)]
        together = await asyncio.gather(*(_one(provider, _req(s, tier, 100 + i, timeout)) for i in range(concurrency)))
        rows.append({"kind": s["kind"], "alone": alone, "together": list(together)})
    return rows


def table(rows: list[dict[str, Any]], label: str, concurrency: int) -> str:
    def med(xs):
        return f"{statistics.median([x[0] for x in xs]):.1f}s" if xs else "-"

    out = [f"### {label} ({time.strftime('%Y-%m-%d %H:%M')})", "",
           f"| question | alone (median) | {concurrency} at once (median / slowest) | valid answers | sample answer |",
           "|---|---|---|---|---|"]
    for r in rows:
        ok = sum(x[1] for x in r["alone"] + r["together"])
        n = len(r["alone"]) + len(r["together"])
        slowest = max(x[0] for x in r["together"]) if r["together"] else 0
        out.append(f"| {r['kind']} | {med(r['alone'])} | {med(r['together'])} / {slowest:.1f}s | {ok}/{n} | "
                   f"`{r['alone'][0][2] if r['alone'] else ''}` |")
    return "\n".join(out) + "\n"


def write(md: str, path: Path = Path("docs/ANIMUS-BENCH.md")) -> None:
    head = ("# Animus provider benchmark\n\nGenerated by `anima animus bench`. "
            "Sample questions: `anima/animus/bench.py` SAMPLES.\n\n")
    text = path.read_text(encoding="utf-8") if path.exists() else head
    path.write_text(text + "\n" + md, encoding="utf-8")
