"""Generate docs/ANIMUS-KNOBS.md: every value an Animus layer may change, from the packages (D27)."""
from __future__ import annotations

from pathlib import Path

from anima.sigil.program import load_agent


def _range(spec: dict) -> str:
    if spec["type"] == "number":
        return f"{spec['min']}..{spec['max']}" + (f", step ≤ {spec['step']}" if "step" in spec else "")
    if "max_len" in spec:
        return f"≤ {spec['max_len']} entries"
    return ""


def render(agents_dir: Path, packages_dir: Path) -> str:
    progs = {m.stem: load_agent(m, packages_dir) for m in sorted(agents_dir.glob("*.yaml"))}
    policy: dict[str, dict] = {}
    weight: dict[str, dict] = {}
    for name, prog in progs.items():
        for k, spec in prog.knobs.items():
            row = policy.setdefault(k, {"spec": spec, "layer": prog.knob_origin[k], "agents": [], "values": set()})
            row["agents"].append(name)
            row["values"].add(repr(prog.policies.get(k)) if not isinstance(prog.policies.get(k), list)
                              else f"{len(prog.policies[k])} entries")
        for b, rng in prog.weight_knobs().items():
            it = prog.behaviors[b]
            row = weight.setdefault(b, {"range": rng, "layer": it.layer, "agents": [], "w": it.spec.get("weight", 1.0)})
            row["agents"].append(name)
    out = ["# Animus knobs",
           "",
           "Generated by `anima animus knobs-doc` from the packages. Do not edit by hand.",
           "An Animus layer (`animus:party`, `animus:NAME`) may change these values and nothing else (D27).",
           "Key format for patches: `policy.NAME`, `weight.BEHAVIOR`.",
           "",
           "- **party**: only the party layer (strategist) may set it.",
           "- **grow only**: may add to the package's list, never remove from it.",
           "- A key set by the party layer is locked for agent layers while it holds (D26).",
           "",
           "## Policies",
           "",
           "| key | type | range | scope | declared in | package value | agents |",
           "|---|---|---|---|---|---|---|"]
    for k in sorted(policy):
        r = policy[k]
        s = r["spec"]
        scope = "party" if s.get("party") else "party or agent"
        if s.get("grow_only"):
            scope += ", grow only"
        agents = "all" if len(r["agents"]) == len(progs) else ", ".join(r["agents"])
        out.append(f"| `policy.{k}` | {s['type']} | {_range(s)} | {scope} | {r['layer']} | "
                   f"{' / '.join(sorted(r['values']))} | {agents} |")
    out += ["", "## Behavior weights (opt-in, efficiency behaviors only)", "",
            "Survival and recovery behaviors (rest, sleep, eat, drink, stand up) and all reflexes never opt in.", "",
            "| key | range | package weight | declared in | agents |", "|---|---|---|---|---|"]
    for b in sorted(weight):
        r = weight[b]
        out.append(f"| `weight.{b}` | {r['range'][0]}..{r['range'][1]} | {r['w']} | {r['layer']} | {', '.join(r['agents'])} |")
    return "\n".join(out) + "\n"


def write_doc(agents_dir: Path, packages_dir: Path, out: Path) -> Path:
    out.write_text(render(agents_dir, packages_dir), encoding="utf-8")
    return out
